### PR TITLE
implement a FactAnalyzer to determine the host type

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Comment by evgeni** [comment]
@sideangleside @Rocco83 @mossicrue this is what we talked about last week. The interesting part is in `lib/katello_attach_subscription/fact_analyzer.rb`, rest is just tests and fixtures and stuff :)

**Comment by mossicrue** [comment]
I try to use function of FactAnalyzer.
If an hypervisor has no guest on it the function system_type return 'unknown' instead of 'hypervisor'

**Comment by evgeni** [comment]
Correct, if there are no facts and no guests, it currently returns unknown. What information would you use in this caee?

**Comment by mossicrue** [comment]
I search facts named 'virt', if its present, the host could be a vm or a physical one, else it's an Hypervisor

**Comment by evgeni** [comment]
In which case would we not have the hypervisor::* facts set at the same time?

**Comment by mossicrue** [comment]
If you mean the ones we gather from virt-who yes, but from a quick analysis, hypervisors seems not have any particular facts

**Comment by evgeni** [comment]
Yeah, I was acting/writing under the assumption that we have either https://github.com/Katello/katello/pull/7821 merged, or implement https://github.com/RedHatSatellite/katello-attach-subscription/issues/32 as a generic-ish workaround, so that we *always* have access to facts

**Comment by mossicrue** [comment]
tested and works

**Pull request merged**
