### PR TITLE
Subscription_Id needs to be changed to id for proper removal

### PR DESCRIPTION
**Pull request by Klaas-**

### CODE REVIEW

**Comment by evgeni** [comment]
I agree with the second part, but don't understand the first one :(

subscription_id is i katello 2 that, what cp_id is in 3
comparing to id will be always false, as that is numeric in katello 3

**Comment by Klaas-** [comment]
I didn't check against katello 2, I guess it depends on the view point - I thought you should add the internal katello id of your subscription as sub (not sure what cp_id is)
-> hammer subscription list --organization-id 1 <-- that id is what I thought you should use in sub
that id corresponds to sub['id']
sub['subscription_id'] is '1' for first subscription of a server and 2 for second ... its the uniq index field I'd guess :)

**Comment by evgeni** [comment]
in the yaml you put the "pool id" which is the longish hash one and that is in cp_id now.

**Comment by Klaas-** [comment]
I'll redo the pull request against master with the readme update, although I'm not 100% sure whats the best way to get that pool id number from katello :)

**Pull request closed without merging**
