### PR TITLE
Clarify sub in README

### PR DESCRIPTION
**Pull request by Klaas-**

### CODE REVIEW

**Comment by Klaas-** [comment]
@evgeni I think your tool is not needed anymore, katello 3.0.2 automatically attaches subscriptions to hypervisors here if they have redhat vms running

**Comment by evgeni** [comment]
@Klaas- so does katello 2.x, but you have no way to contoll which sub the hypervisor will get, thats why I wrote this.

otherweise hypervisors end up with "up to 1 guest" subs and other funny combinations :(

**Comment by Klaas-** [comment]
hehe, it never worked in 2.4 for me .. :) but yeah I didn't think about the multiple licenses issue - my company only has one kind of hypervisors :)

**Comment by evgeni** [comment]
lucky you :)

**Pull request merged**
